# Generated by Django 5.1.2 on 2024-11-19 19:47

import bots.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysistask',
            name='analysis_sub_type',
            field=models.IntegerField(choices=[(1, 'Deepgram'), (2, 'Recording Generation Standard')]),
        ),
        migrations.AlterField(
            model_name='analysistask',
            name='analysis_type',
            field=models.IntegerField(choices=[(1, 'Speech Transcription'), (2, 'Recording Generation')]),
        ),
        migrations.CreateModel(
            name='RecordingUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=bots.models.RecordingStorage(), upload_to='%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recording_uploads', to='bots.analysistask')),
            ],
        ),
    ]
