# Generated by Django 5.1.2 on 2024-11-19 20:43

import bots.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0002_alter_analysistask_analysis_sub_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='name',
            field=models.CharField(default='My bot', max_length=255),
        ),
        migrations.AlterField(
            model_name='recordingupload',
            name='file',
            field=models.FileField(storage=bots.models.RecordingStorage(), upload_to=''),
        ),
    ]
