# Generated by Django 5.1.2 on 2024-12-15 07:02

import concurrency.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0002_mediablob_botmediarequest_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bot',
            name='valid_state_substate_combinations',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='sub_state',
        ),
        migrations.RemoveField(
            model_name='botevent',
            name='new_sub_state',
        ),
        migrations.RemoveField(
            model_name='botevent',
            name='old_sub_state',
        ),
        migrations.AddField(
            model_name='botevent',
            name='debug_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='botevent',
            name='event_sub_type',
            field=models.IntegerField(choices=[(1, 'Bot could not join meeting - Meeting Not Started - Waiting for Host'), (2, 'Fatal error - Process Terminated')], null=True),
        ),
        migrations.AddField(
            model_name='botevent',
            name='requested_bot_action_taken_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bot',
            name='state',
            field=models.IntegerField(choices=[(1, 'Ready'), (2, 'Joining'), (3, 'Joined - Not Recording'), (4, 'Joined - Recording'), (5, 'Leaving'), (6, 'Ended'), (7, 'Fatal Error'), (8, 'Waiting Room')], default=1),
        ),
        migrations.AlterField(
            model_name='botevent',
            name='event_type',
            field=models.IntegerField(choices=[(1, 'Bot Put in Waiting Room'), (2, 'Bot Joined Meeting'), (3, 'Bot Recording Permission Granted'), (4, 'Meeting Ended'), (5, 'Bot Left Meeting'), (6, 'Bot requested to join meeting'), (7, 'Bot Encountered Fatal error'), (8, 'Bot requested to leave meeting'), (9, 'Bot could not join meeting')]),
        ),
        migrations.AlterField(
            model_name='botevent',
            name='new_state',
            field=models.IntegerField(choices=[(1, 'Ready'), (2, 'Joining'), (3, 'Joined - Not Recording'), (4, 'Joined - Recording'), (5, 'Leaving'), (6, 'Ended'), (7, 'Fatal Error'), (8, 'Waiting Room')]),
        ),
        migrations.AlterField(
            model_name='botevent',
            name='old_state',
            field=models.IntegerField(choices=[(1, 'Ready'), (2, 'Joining'), (3, 'Joined - Not Recording'), (4, 'Joined - Recording'), (5, 'Leaving'), (6, 'Ended'), (7, 'Fatal Error'), (8, 'Waiting Room')]),
        ),
        migrations.AlterField(
            model_name='botevent',
            name='version',
            field=concurrency.fields.IntegerVersionField(default=0, help_text='record revision number'),
        ),
        migrations.AddConstraint(
            model_name='botevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('event_type', 7), ('event_sub_type', 2)), models.Q(('event_type', 9), ('event_sub_type', 1)), models.Q(models.Q(('event_type', 7), _negated=True), models.Q(('event_type', 9), _negated=True), ('event_sub_type__isnull', True)), _connector='OR'), name='valid_event_type_event_sub_type_combinations'),
        ),
    ]
