# Generated by Django 5.1.2 on 2024-11-22 19:39

import bots.models
import concurrency.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0003_bot_name_alter_recordingupload_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordingupload',
            name='analysis_task',
        ),
        migrations.RemoveField(
            model_name='utterance',
            name='bot',
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recording_type', models.IntegerField(choices=[(1, 'Audio and Video'), (2, 'Audio Only')])),
                ('transcription_type', models.IntegerField(choices=[(1, 'Standard'), (2, 'Realtime'), (3, 'No Transcription')])),
                ('is_default_recording', models.BooleanField(default=False)),
                ('state', models.IntegerField(choices=[(1, 'Not Started'), (2, 'In Progress'), (3, 'Complete'), (4, 'Failed')], default=1)),
                ('transcription_state', models.IntegerField(choices=[(1, 'Not Started'), (2, 'In Progress'), (3, 'Complete'), (4, 'Failed')], default=1)),
                ('transcription_provider', models.IntegerField(blank=True, choices=[(1, 'Deepgram')], null=True)),
                ('version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('file', models.FileField(storage=bots.models.RecordingStorage(), upload_to='')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='bots.bot')),
            ],
        ),
        migrations.AddField(
            model_name='utterance',
            name='recording',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='utterances', to='bots.recording'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AnalysisTask',
        ),
        migrations.DeleteModel(
            name='RecordingUpload',
        ),
    ]
