# Generated by Django 5.1.2 on 2024-12-26 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0003_remove_bot_valid_state_substate_combinations_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='botevent',
            name='valid_event_type_event_sub_type_combinations',
        ),
        migrations.AlterField(
            model_name='botevent',
            name='event_sub_type',
            field=models.IntegerField(choices=[(1, 'Bot could not join meeting - Meeting Not Started - Waiting for Host'), (2, 'Fatal error - Process Terminated'), (3, 'Bot could not join meeting - Zoom Authorization Failed')], null=True),
        ),
        migrations.AddConstraint(
            model_name='botevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('event_type', 7), ('event_sub_type', 2)), models.Q(('event_type', 9), models.Q(('event_sub_type', 1), ('event_sub_type', 3), _connector='OR')), models.Q(models.Q(('event_type', 7), _negated=True), models.Q(('event_type', 9), _negated=True), ('event_sub_type__isnull', True)), _connector='OR'), name='valid_event_type_event_sub_type_combinations'),
        ),
    ]
