# Generated by Django 5.1.2 on 2024-12-01 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0004_remove_recordingupload_analysis_task_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utterance',
            old_name='timeline_ms',
            new_name='timestamp_ms',
        ),
        migrations.AddField(
            model_name='recording',
            name='first_buffer_timestamp_ms',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
