# Generated by Django 5.1.2 on 2024-12-01 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0005_rename_timeline_ms_utterance_timestamp_ms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='first_buffer_timestamp_ms',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='utterance',
            name='timestamp_ms',
            field=models.BigIntegerField(),
        ),
    ]
