# Generated by Django 5.1.2 on 2025-01-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0005_utterance_source_utterance_source_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='settings',
            field=models.JSONField(default=dict),
        ),
    ]
