# Generated by Django 5.1.2 on 2025-02-03 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0009_remove_botevent_valid_event_type_event_sub_type_combinations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botmediarequest',
            name='text_to_speak',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='botmediarequest',
            name='text_to_speech_settings',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='botmediarequest',
            name='media_blob',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bot_media_requests', to='bots.mediablob'),
        ),
    ]
