# Generated by Django 5.1.2 on 2025-02-23 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0013_remove_botevent_valid_event_type_event_sub_type_combinations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utterance',
            name='sample_rate',
            field=models.IntegerField(default=32000),
        ),
    ]
