# Generated by Django 5.1.2 on 2025-03-22 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_organization_centicredits_organization_version'),
        ('bots', '0016_remove_botevent_valid_event_type_event_sub_type_combinations_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('centicredits_before', models.IntegerField()),
                ('centicredits_after', models.IntegerField()),
                ('centicredits_delta', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('bot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_transactions', to='bots.bot')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_transactions', to='accounts.organization')),
                ('parent_transaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_transactions', to='bots.credittransaction')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('parent_transaction__isnull', False)), fields=('parent_transaction',), name='unique_child_transaction'), models.UniqueConstraint(condition=models.Q(('parent_transaction__isnull', True)), fields=('organization',), name='unique_root_transaction'), models.UniqueConstraint(condition=models.Q(('bot__isnull', False)), fields=('bot',), name='unique_bot_transaction')],
            },
        ),
    ]
