# Generated by Django 5.1.2 on 2025-03-27 05:41

import bots.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0017_credittransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookSecret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_secret', models.BinaryField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_secrets', to='bots.project')),
            ],
        ),
        migrations.CreateModel(
            name='WebhookSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(editable=False, max_length=32, unique=True)),
                ('url', models.URLField()),
                ('triggers', models.JSONField(default=bots.models.WebhookSubscription.default_triggers)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_subscriptions', to='bots.project')),
            ],
        ),
        migrations.CreateModel(
            name='WebhookDeliveryAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_trigger_type', models.IntegerField(choices=[(1, 'Bot State Change')], default=1)),
                ('idempotency_key', models.UUIDField(editable=False, unique=True)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Success'), (3, 'Failure')], default=1)),
                ('attempt_count', models.IntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('succeeded_at', models.DateTimeField(blank=True, null=True)),
                ('response_body_list', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_delivery_attempts', to='bots.bot')),
                ('webhook_subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhookdelivery_attempts', to='bots.webhooksubscription')),
            ],
        ),
    ]
