# Generated by Django 5.1.2 on 2025-03-31 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_organization_is_webhooks_enabled'),
        ('bots', '0018_webhooksecret_webhooksubscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='credittransaction',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='credittransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('stripe_payment_intent_id__isnull', False)), fields=('stripe_payment_intent_id',), name='unique_stripe_payment_intent_id'),
        ),
    ]
