# Generated by Django 5.1.2 on 2025-04-12 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0021_remove_botevent_valid_event_type_event_sub_type_combinations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
