# Generated by Django 5.1.2 on 2025-04-25 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0022_bot_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='transcription_provider',
            field=models.IntegerField(blank=True, choices=[(1, 'Deepgram'), (2, 'Closed Caption From Platform'), (3, 'Gladia')], null=True),
        ),
    ]
