# Generated by Django 5.1.2 on 2025-05-01 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0026_alter_bot_state_alter_botevent_event_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botmediarequest',
            name='media_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='botmediarequest',
            name='media_type',
            field=models.IntegerField(choices=[(1, 'Image'), (2, 'Audio'), (3, 'Video')]),
        ),
    ]
