# Generated by Django 5.1.2 on 2025-05-08 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0027_remove_botevent_valid_event_type_event_sub_type_combinations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botmediarequest',
            name='media_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='botmediarequest',
            name='media_type',
            field=models.IntegerField(choices=[(1, 'Image'), (2, 'Audio'), (3, 'Video')]),
        ),
    ]
