# Generated by Django 5.1.2 on 2025-05-23 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0029_recording_transcription_failure_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('to', models.IntegerField(choices=[(1, 'only_bot'), (2, 'everyone')])),
                ('timestamp', models.IntegerField()),
                ('additional_data', models.JSONField(default=dict)),
                ('object_id', models.CharField(editable=False, max_length=32, unique=True)),
                ('source_uuid', models.CharField(max_length=255, null=True, unique=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='bots.bot')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='bots.participant')),
            ],
        ),
    ]
