# Generated by Django 5.1.2 on 2025-06-06 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0032_alter_webhookdeliveryattempt_webhook_trigger_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotChatMessageRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_user_uuid', models.CharField(blank=True, max_length=255, null=True)),
                ('to', models.CharField(choices=[('everyone', 'Everyone'), ('specific_user', 'Specific User'), ('everyone_but_host', 'Everyone But Host')])),
                ('message', models.TextField()),
                ('additional_data', models.JSONField(default=dict)),
                ('state', models.IntegerField(choices=[(1, 'Enqueued'), (2, 'Sent'), (3, 'Failed')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at_timestamp_ms', models.BigIntegerField(blank=True, null=True)),
                ('failure_data', models.JSONField(default=None, null=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_message_requests', to='bots.bot')),
            ],
        ),
    ]
