# Generated by Django 5.1.2 on 2025-06-15 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0035_bot_join_at_alter_bot_state_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bot',
            index=models.Index(condition=models.Q(('join_at__isnull', False)), fields=['join_at'], name='bot_join_at_idx'),
        ),
    ]
