# Generated by Django 5.1.2 on 2025-06-17 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0036_bot_bot_join_at_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='state',
            field=models.IntegerField(choices=[(1, 'Ready'), (2, 'Joining'), (3, 'Joined - Not Recording'), (4, 'Joined - Recording'), (5, 'Leaving'), (6, 'Post Processing'), (7, 'Fatal Error'), (8, 'Waiting Room'), (9, 'Ended'), (10, 'Data Deleted'), (11, 'Scheduled'), (12, 'Staged'), (13, 'Joined - Recording Paused')], default=1),
        ),
        migrations.AlterField(
            model_name='botevent',
            name='event_type',
            field=models.IntegerField(choices=[(1, 'Bot Put in Waiting Room'), (2, 'Bot Joined Meeting'), (3, 'Bot Recording Permission Granted'), (4, 'Meeting Ended'), (5, 'Bot Left Meeting'), (6, 'Bot requested to join meeting'), (7, 'Bot Encountered Fatal error'), (8, 'Bot requested to leave meeting'), (9, 'Bot could not join meeting'), (10, 'Post Processing Completed'), (11, 'Data Deleted'), (12, 'Bot staged'), (13, 'Recording Paused'), (14, 'Recording Resumed')]),
        ),
        migrations.AlterField(
            model_name='botevent',
            name='new_state',
            field=models.IntegerField(choices=[(1, 'Ready'), (2, 'Joining'), (3, 'Joined - Not Recording'), (4, 'Joined - Recording'), (5, 'Leaving'), (6, 'Post Processing'), (7, 'Fatal Error'), (8, 'Waiting Room'), (9, 'Ended'), (10, 'Data Deleted'), (11, 'Scheduled'), (12, 'Staged'), (13, 'Joined - Recording Paused')]),
        ),
        migrations.AlterField(
            model_name='botevent',
            name='old_state',
            field=models.IntegerField(choices=[(1, 'Ready'), (2, 'Joining'), (3, 'Joined - Not Recording'), (4, 'Joined - Recording'), (5, 'Leaving'), (6, 'Post Processing'), (7, 'Fatal Error'), (8, 'Waiting Room'), (9, 'Ended'), (10, 'Data Deleted'), (11, 'Scheduled'), (12, 'Staged'), (13, 'Joined - Recording Paused')]),
        ),
        migrations.AlterField(
            model_name='recording',
            name='state',
            field=models.IntegerField(choices=[(1, 'Not Started'), (2, 'In Progress'), (3, 'Complete'), (4, 'Failed'), (5, 'Paused')], default=1),
        ),
    ]
