# Generated by Django 5.1.2 on 2025-06-27 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0040_alter_webhookdeliveryattempt_webhook_trigger_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhooksubscription',
            name='bot',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='bot_webhook_subscriptions',
                to='bots.bot'
            ),
        ),
    ]
