# Generated by Django 5.1.2 on 2025-06-27 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0040_alter_webhookdeliveryattempt_webhook_trigger_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='is_the_bot',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='object_id',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='webhookdeliveryattempt',
            name='webhook_trigger_type',
            field=models.IntegerField(choices=[(1, 'Bot State Change'), (2, 'Transcript Update'), (3, 'Chat Messages Update'), (4, 'Participant Join/Leave')], default=1),
        ),
        migrations.CreateModel(
            name='ParticipantEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.IntegerField(choices=[(1, 'Join'), (2, 'Leave')])),
                ('object_id', models.CharField(editable=False, max_length=255, unique=True)),
                ('event_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('timestamp_ms', models.BigIntegerField()),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='bots.participant')),
            ],
        ),
    ]
