# Generated by Django 5.1.2 on 2025-07-29 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0048_projectaccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botevent',
            name='event_sub_type',
            field=models.IntegerField(choices=[(1, 'Bot could not join meeting - Meeting Not Started - Waiting for Host'), (2, 'Fatal error - Process Terminated'), (3, 'Bot could not join meeting - Zoom Authorization Failed'), (4, 'Bot could not join meeting - Zoom Meeting Status Failed'), (5, 'Bot could not join meeting - Unpublished Zoom Apps cannot join external meetings. See https://developers.zoom.us/docs/distribute/sdk-feature-review-requirements/'), (6, 'Fatal error - RTMP Connection Failed'), (7, 'Bot could not join meeting - Zoom SDK Internal Error'), (8, 'Fatal error - UI Element Not Found'), (9, 'Bot could not join meeting - Request to join denied'), (10, 'Leave requested - User requested'), (11, 'Leave requested - Auto leave silence'), (12, 'Leave requested - Auto leave only participant in meeting'), (13, 'Fatal error - Heartbeat timeout'), (14, 'Bot could not join meeting - Meeting not found'), (15, 'Fatal error - Bot not launched'), (16, 'Bot could not join meeting - Waiting room timeout exceeded'), (17, 'Leave requested - Auto leave max uptime exceeded'), (18, 'Bot could not join meeting - Login required. Use signed in bots: https://docs.attendee.dev/guides/signed-in-bots to resolve.'), (19, 'Bot could not join meeting - Bot login attempt failed'), (20, 'Fatal error - Out of credits'), (21, 'Bot could not join meeting - Unable to connect to meeting. This usually means the meeting password in the URL is incorrect.'), (22, 'Fatal error - Attendee internal error')], null=True),
        ),
    ]
