# Generated by Django 5.1.2 on 2025-08-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0049_alter_botevent_event_sub_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='recording_type',
            field=models.IntegerField(choices=[(1, 'Audio and Video'), (2, 'Audio Only'), (3, 'No Recording')]),
        ),
    ]
