# Generated by Django 5.1.2 on 2025-08-18 03:00

import concurrency.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0051_alter_credentials_credential_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhookdeliveryattempt',
            name='webhook_trigger_type',
            field=models.IntegerField(choices=[(1, 'Bot State Change'), (2, 'Transcript Update'), (3, 'Chat Messages Update'), (4, 'Participant Join/Leave'), (5, 'Calendar Events Update'), (6, 'Calendar State Change')], default=1),
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(editable=False, max_length=32, unique=True)),
                ('platform', models.CharField(choices=[('google', 'Google'), ('microsoft', 'Microsoft')], max_length=255)),
                ('state', models.IntegerField(choices=[(1, 'Connected'), (2, 'Disconnected')], default=1)),
                ('connection_failure_data', models.JSONField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('deduplication_key', models.CharField(blank=True, help_text='Optional key for deduplicating calendars', max_length=1024, null=True)),
                ('client_id', models.CharField(max_length=255)),
                ('platform_uuid', models.CharField(blank=True, max_length=1024, null=True)),
                ('last_attempted_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_successful_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_successful_sync_time_window_start', models.DateTimeField(blank=True, null=True)),
                ('last_successful_sync_time_window_end', models.DateTimeField(blank=True, null=True)),
                ('last_successful_sync_started_at', models.DateTimeField(blank=True, null=True)),
                ('sync_task_enqueued_at', models.DateTimeField(blank=True, null=True)),
                ('sync_task_requested_at', models.DateTimeField(blank=True, null=True)),
                ('_encrypted_data', models.BinaryField(null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calendars', to='bots.project')),
            ],
        ),
        migrations.AddField(
            model_name='webhookdeliveryattempt',
            name='calendar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_delivery_attempts', to='bots.calendar'),
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(editable=False, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform_uuid', models.CharField(max_length=1024)),
                ('meeting_url', models.CharField(blank=True, max_length=511, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('attendees', models.JSONField(blank=True, null=True)),
                ('ical_uid', models.CharField(blank=True, max_length=1024, null=True)),
                ('name', models.CharField(blank=True, max_length=1024, null=True)),
                ('raw', models.JSONField()),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='bots.calendar')),
            ],
        ),
        migrations.AddField(
            model_name='bot',
            name='calendar_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bots', to='bots.calendarevent'),
        ),
        migrations.AddConstraint(
            model_name='calendar',
            constraint=models.UniqueConstraint(fields=('project', 'deduplication_key'), name='unique_calendar_deduplication_key'),
        ),
        migrations.AddConstraint(
            model_name='calendarevent',
            constraint=models.UniqueConstraint(fields=('calendar', 'platform_uuid'), name='unique_calendar_event_platform_uuid'),
        ),
    ]
