# Generated by Django 5.1.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0054_alter_credentials_credential_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botchatmessagerequest',
            name='to',
            field=models.CharField(max_length=50, choices=[('everyone', 'Everyone'), ('specific_user', 'Specific User'), ('everyone_but_host', 'Everyone But Host')]),
        ),
    ]