[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "/opt/bin/entrypoint.sh && python manage.py migrate && gunicorn attendee.wsgi:application --bind 0.0.0.0:$PORT --workers 4 --timeout 120"
healthcheckPath = "/admin/login/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10