from django.urls import path

from . import projects_views

app_name = "bots"

urlpatterns = [
    path(
        "create/",
        projects_views.CreateProjectView.as_view(),
        name="create-project",
    ),
    path(
        "<str:object_id>",
        projects_views.ProjectDashboardView.as_view(),
        name="project-dashboard",
    ),
    path(
        "<str:object_id>/bots",
        projects_views.ProjectBotsView.as_view(),
        name="project-bots",
    ),
    path(
        "<str:object_id>/bots/create",
        projects_views.CreateBotView.as_view(),
        name="create-bot",
    ),
    path(
        "<str:object_id>/bots/<str:bot_object_id>",
        projects_views.ProjectBotDetailView.as_view(),
        name="project-bot-detail",
    ),
    path(
        "<str:object_id>/bots/<str:bot_object_id>/recordings",
        projects_views.ProjectBotRecordingsView.as_view(),
        name="project-bot-recordings",
    ),
    path(
        "<str:object_id>/credentials",
        projects_views.ProjectCredentialsView.as_view(),
        name="project-credentials",
    ),
    path(
        "<str:object_id>/project",
        projects_views.ProjectProjectView.as_view(),
        name="project-project",
    ),
    path(
        "<str:object_id>/edit",
        projects_views.EditProjectView.as_view(),
        name="project-edit",
    ),
    path(
        "<str:object_id>/keys",
        projects_views.ProjectApiKeysView.as_view(),
        name="project-api-keys",
    ),
    path(
        "<str:object_id>/keys/create/",
        projects_views.CreateApiKeyView.as_view(),
        name="create-api-key",
    ),
    path(
        "<str:object_id>/keys/<str:key_object_id>/delete/",
        projects_views.DeleteApiKeyView.as_view(),
        name="delete-api-key",
    ),
    path(
        "<str:object_id>/settings/credentials/",
        projects_views.CreateCredentialsView.as_view(),
        name="create-credentials",
    ),
    path(
        "<str:object_id>/webhooks/",
        projects_views.ProjectWebhooksView.as_view(),
        name="project-webhooks",
    ),
    path(
        "<str:object_id>/webhooks/create/",
        projects_views.CreateWebhookView.as_view(),
        name="create-webhook",
    ),
    path(
        "<str:object_id>/webhooks/<str:webhook_object_id>/delete/",
        projects_views.DeleteWebhookView.as_view(),
        name="delete-webhook",
    ),
    path(
        "<str:object_id>/billing/",
        projects_views.ProjectBillingView.as_view(),
        name="project-billing",
    ),
    path(
        "<str:object_id>/billing/checkout/",
        projects_views.CreateCheckoutSessionView.as_view(),
        name="create-checkout-session",
    ),
    path(
        "<str:object_id>/billing/checkout/success/",
        projects_views.CheckoutSuccessView.as_view(),
        name="checkout-success",
    ),
    path(
        "<str:object_id>/team/",
        projects_views.ProjectTeamView.as_view(),
        name="project-team",
    ),
    path(
        "<str:object_id>/team/invite/",
        projects_views.InviteUserView.as_view(),
        name="invite-user",
    ),
    path(
        "<str:object_id>/team/users/edit",
        projects_views.EditUserView.as_view(),
        name="edit-user",
    ),
    # Don't put anything after this, it will redirect to the dashboard
    path(
        "<str:object_id>/",
        projects_views.RedirectToDashboardView.as_view(),
        name="project-unrecognized",
    ),
    path(
        "<str:object_id>/<path:extra>",
        projects_views.RedirectToDashboardView.as_view(),
        name="project-unrecognized",
    ),
]
