# Generated by Django 5.1.2 on 2025-03-09 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='centicredits',
            field=models.IntegerField(default=500),
        ),
    ]
