# Generated by Django 5.1.2 on 2025-03-22 18:01

import concurrency.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='centicredits',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='organization',
            name='version',
            field=concurrency.fields.IntegerVersionField(default=0, help_text='record revision number'),
        ),
    ]
