# Generated by Django 5.1.2 on 2025-03-27 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_organization_centicredits_organization_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_webhooks_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
