# Generated by Django 5.1.2 on 2025-04-14 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_organization_is_webhooks_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='is_webhooks_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
