# Generated by Django 5.1.2 on 2025-04-15 00:10

from django.db import migrations

def enable_webhooks_for_all_organizations(apps, schema_editor):
    # Get the historical model
    Organization = apps.get_model('accounts', 'Organization')
    
    # Update all organizations
    Organization.objects.all().update(is_webhooks_enabled=True)


def reverse_webhooks_enablement(apps, schema_editor):
    # No reverse operation needed, but included for completeness
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_organization_is_webhooks_enabled'),
    ]

    operations = [
        migrations.RunPython(enable_webhooks_for_all_organizations, reverse_webhooks_enablement),
    ]