# Generated by Django 5.1.2 on 2025-07-25 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_invited_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('regular_user', 'Regular User')], default='admin', max_length=255),
        ),
    ]
