# Generated by Django 5.1.2 on 2025-07-29 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='object_id',
            field=models.CharField(blank=True, editable=False, max_length=32, null=True, unique=True),
        ),
    ]
