# Generated by Django 5.1.2 on 2025-07-29 18:57

from django.db import migrations
import random
import string

def forwards(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    for user in User.objects.all():        
        # Since custom save() won't be called, manually generate object_id if None
        if not user.object_id:
            rand = "".join(random.choices(string.ascii_letters + string.digits, k=16))
            user.object_id = f"usr_{rand}"
            user.save()
            
        print(f"User {user.id} has object_id {user.object_id}")

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_object_id'),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
