# Generated by Django 5.1.2 on 2025-07-29 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20250729_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='object_id',
            field=models.CharField(editable=False, max_length=32, unique=True),
        ),
    ]
