# Generated by Django 5.1.2 on 2025-08-25 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='autopay_amount_to_purchase_cents',
            field=models.IntegerField(default=5000),
        ),
        migrations.AddField(
            model_name='organization',
            name='autopay_charge_failure_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='autopay_charge_task_enqueued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='autopay_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='autopay_stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='autopay_threshold_centricredits',
            field=models.IntegerField(default=1000),
        ),
    ]
